baseURL = "https://tic40.github.io"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
paginate = 4
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "tic40.github.io"
googleAnalytics = "UA-57261073-4"
[author]
  picPath = "https://avatars2.githubusercontent.com/u/739402?s=460&v=4"
  homepageText = "tic40.github.io"
  name = "tic40"
  github = "https://github.com/tic40"
  facebook = "https://facebook.com/taishi40"
  twitter = "https://twitter.com/tic40"
  qiita = "https://qiita.com/tic40"
  blog = "https://tic40.hatenablog.com"
  hackerrank = "https://www.hackerrank.com/tic40"
  freecodecamp = "https://www.freecodecamp.org/tic40"
  booklog = "https://booklog.jp/users/tic40"
[params]
  description = "tic40.github.io"
  disqusShortname = "tic40"
  licence = ""
  adsenseDataAdClient = ""
  adsenseDataAdSlot = ""
[permalinks]
  posts = "/:year/:month/:day/:slug/"
[pygmentsOptions]
  linenos = false
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "Profile"
  weight = -100
  identifier = "profile"
  url = "/profile/"
